/**
 * Cloudmersive
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['invoker/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Cloudmersive) {
      root.Cloudmersive = {};
    }
    root.Cloudmersive.InlineResponse20018FoundViruses = factory(root.Cloudmersive.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse20018FoundViruses model module.
   * @module invoker/model/InlineResponse20018FoundViruses
   * @version 1.2.1
   */

  /**
   * Constructs a new <code>InlineResponse20018FoundViruses</code>.
   * Virus positively identified
   * @alias module:invoker/model/InlineResponse20018FoundViruses
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>InlineResponse20018FoundViruses</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:invoker/model/InlineResponse20018FoundViruses} obj Optional instance to populate.
   * @return {module:invoker/model/InlineResponse20018FoundViruses} The populated <code>InlineResponse20018FoundViruses</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('FileName')) {
        obj['FileName'] = ApiClient.convertToType(data['FileName'], 'String');
      }
      if (data.hasOwnProperty('VirusName')) {
        obj['VirusName'] = ApiClient.convertToType(data['VirusName'], 'String');
      }
    }
    return obj;
  }

  /**
   * Name of the file containing the virus
   * @member {String} FileName
   */
  exports.prototype['FileName'] = undefined;
  /**
   * Name of the virus that was found
   * @member {String} VirusName
   */
  exports.prototype['VirusName'] = undefined;



  return exports;
}));


