/**
 * Cloudmersive
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['invoker/ApiClient', 'invoker/model/InlineResponse2008Word'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse2008Word'));
  } else {
    // Browser globals (root is window)
    if (!root.Cloudmersive) {
      root.Cloudmersive = {};
    }
    root.Cloudmersive.InlineResponse2008Words = factory(root.Cloudmersive.ApiClient, root.Cloudmersive.InlineResponse2008Word);
  }
}(this, function(ApiClient, InlineResponse2008Word) {
  'use strict';




  /**
   * The InlineResponse2008Words model module.
   * @module invoker/model/InlineResponse2008Words
   * @version 1.2.1
   */

  /**
   * Constructs a new <code>InlineResponse2008Words</code>.
   * A word in a sentence
   * @alias module:invoker/model/InlineResponse2008Words
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>InlineResponse2008Words</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:invoker/model/InlineResponse2008Words} obj Optional instance to populate.
   * @return {module:invoker/model/InlineResponse2008Words} The populated <code>InlineResponse2008Words</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Word')) {
        obj['Word'] = InlineResponse2008Word.constructFromObject(data['Word']);
      }
      if (data.hasOwnProperty('Correct')) {
        obj['Correct'] = ApiClient.convertToType(data['Correct'], 'Boolean');
      }
      if (data.hasOwnProperty('Suggestions')) {
        obj['Suggestions'] = ApiClient.convertToType(data['Suggestions'], ['String']);
      }
    }
    return obj;
  }

  /**
   * @member {module:invoker/model/InlineResponse2008Word} Word
   */
  exports.prototype['Word'] = undefined;
  /**
   * True if the word is spelled correctly, false otherwise
   * @member {Boolean} Correct
   */
  exports.prototype['Correct'] = undefined;
  /**
   * Suggested spelling improvements
   * @member {Array.<String>} Suggestions
   */
  exports.prototype['Suggestions'] = undefined;



  return exports;
}));


