/**
 * Cloudmersive
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['invoker/ApiClient', 'invoker/model/InlineResponse2008Words'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse2008Words'));
  } else {
    // Browser globals (root is window)
    if (!root.Cloudmersive) {
      root.Cloudmersive = {};
    }
    root.Cloudmersive.InlineResponse2008 = factory(root.Cloudmersive.ApiClient, root.Cloudmersive.InlineResponse2008Words);
  }
}(this, function(ApiClient, InlineResponse2008Words) {
  'use strict';




  /**
   * The InlineResponse2008 model module.
   * @module invoker/model/InlineResponse2008
   * @version 1.2.1
   */

  /**
   * Constructs a new <code>InlineResponse2008</code>.
   * Result of spell checking a sentence
   * @alias module:invoker/model/InlineResponse2008
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>InlineResponse2008</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:invoker/model/InlineResponse2008} obj Optional instance to populate.
   * @return {module:invoker/model/InlineResponse2008} The populated <code>InlineResponse2008</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('IncorrectCount')) {
        obj['IncorrectCount'] = ApiClient.convertToType(data['IncorrectCount'], 'Number');
      }
      if (data.hasOwnProperty('Words')) {
        obj['Words'] = ApiClient.convertToType(data['Words'], [InlineResponse2008Words]);
      }
    }
    return obj;
  }

  /**
   * Number of incorrect words
   * @member {Number} IncorrectCount
   */
  exports.prototype['IncorrectCount'] = undefined;
  /**
   * Words in the sentence, both correct and incorrect
   * @member {Array.<module:invoker/model/InlineResponse2008Words>} Words
   */
  exports.prototype['Words'] = undefined;



  return exports;
}));


