/**
 * Cloudmersive
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['client.invoker/ApiClient', 'client.invoker/client.model/InlineResponse20013Matches'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse20013Matches'));
  } else {
    // Browser globals (root is window)
    if (!root.Cloudmersive) {
      root.Cloudmersive = {};
    }
    root.Cloudmersive.InlineResponse20013 = factory(root.Cloudmersive.ApiClient, root.Cloudmersive.InlineResponse20013Matches);
  }
}(this, function(ApiClient, InlineResponse20013Matches) {
  'use strict';




  /**
   * The InlineResponse20013 model module.
   * @module client.invoker/client.model/InlineResponse20013
   * @version 1.2.1
   */

  /**
   * Constructs a new <code>InlineResponse20013</code>.
   * @alias module:client.invoker/client.model/InlineResponse20013
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>InlineResponse20013</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:client.invoker/client.model/InlineResponse20013} obj Optional instance to populate.
   * @return {module:client.invoker/client.model/InlineResponse20013} The populated <code>InlineResponse20013</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Successful')) {
        obj['Successful'] = ApiClient.convertToType(data['Successful'], 'Boolean');
      }
      if (data.hasOwnProperty('Matches')) {
        obj['Matches'] = ApiClient.convertToType(data['Matches'], [InlineResponse20013Matches]);
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} Successful
   */
  exports.prototype['Successful'] = undefined;
  /**
   * @member {Array.<module:client.invoker/client.model/InlineResponse20013Matches>} Matches
   */
  exports.prototype['Matches'] = undefined;



  return exports;
}));


