/**
 * Cloudmersive
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['client.invoker/ApiClient', 'client.invoker/client.model/InlineResponse2007Words'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse2007Words'));
  } else {
    // Browser globals (root is window)
    if (!root.Cloudmersive) {
      root.Cloudmersive = {};
    }
    root.Cloudmersive.InlineResponse2007TaggedSentences = factory(root.Cloudmersive.ApiClient, root.Cloudmersive.InlineResponse2007Words);
  }
}(this, function(ApiClient, InlineResponse2007Words) {
  'use strict';




  /**
   * The InlineResponse2007TaggedSentences model module.
   * @module client.invoker/client.model/InlineResponse2007TaggedSentences
   * @version 1.2.1
   */

  /**
   * Constructs a new <code>InlineResponse2007TaggedSentences</code>.
   * Sentence in a POS tag result
   * @alias module:client.invoker/client.model/InlineResponse2007TaggedSentences
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>InlineResponse2007TaggedSentences</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:client.invoker/client.model/InlineResponse2007TaggedSentences} obj Optional instance to populate.
   * @return {module:client.invoker/client.model/InlineResponse2007TaggedSentences} The populated <code>InlineResponse2007TaggedSentences</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Words')) {
        obj['Words'] = ApiClient.convertToType(data['Words'], [InlineResponse2007Words]);
      }
    }
    return obj;
  }

  /**
   * Words in the sentence
   * @member {Array.<module:client.invoker/client.model/InlineResponse2007Words>} Words
   */
  exports.prototype['Words'] = undefined;



  return exports;
}));


