/**
 * Cloudmersive
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['client.invoker/ApiClient', 'client.invoker/client.model/ConverttemplatehtmlapplyOperations'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ConverttemplatehtmlapplyOperations'));
  } else {
    // Browser globals (root is window)
    if (!root.Cloudmersive) {
      root.Cloudmersive = {};
    }
    root.Cloudmersive.Value = factory(root.Cloudmersive.ApiClient, root.Cloudmersive.ConverttemplatehtmlapplyOperations);
  }
}(this, function(ApiClient, ConverttemplatehtmlapplyOperations) {
  'use strict';




  /**
   * The Value model module.
   * @module client.invoker/client.model/Value
   * @version 1.2.1
   */

  /**
   * Constructs a new <code>Value</code>.
   * HTML template application request
   * @alias module:client.invoker/client.model/Value
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Value</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:client.invoker/client.model/Value} obj Optional instance to populate.
   * @return {module:client.invoker/client.model/Value} The populated <code>Value</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('HtmlTemplate')) {
        obj['HtmlTemplate'] = ApiClient.convertToType(data['HtmlTemplate'], 'String');
      }
      if (data.hasOwnProperty('HtmlTemplateUrl')) {
        obj['HtmlTemplateUrl'] = ApiClient.convertToType(data['HtmlTemplateUrl'], 'String');
      }
      if (data.hasOwnProperty('Operations')) {
        obj['Operations'] = ApiClient.convertToType(data['Operations'], [ConverttemplatehtmlapplyOperations]);
      }
    }
    return obj;
  }

  /**
   * @member {String} HtmlTemplate
   */
  exports.prototype['HtmlTemplate'] = undefined;
  /**
   * @member {String} HtmlTemplateUrl
   */
  exports.prototype['HtmlTemplateUrl'] = undefined;
  /**
   * @member {Array.<module:client.invoker/client.model/ConverttemplatehtmlapplyOperations>} Operations
   */
  exports.prototype['Operations'] = undefined;



  return exports;
}));


