/**
 * Cloudmersive
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cloudmersive);
  }
}(this, function(expect, Cloudmersive) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cloudmersive.InlineResponse20018FoundViruses();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse20018FoundViruses', function() {
    it('should create an instance of InlineResponse20018FoundViruses', function() {
      // uncomment below and update the code to test InlineResponse20018FoundViruses
      //var instane = new Cloudmersive.InlineResponse20018FoundViruses();
      //expect(instance).to.be.a(Cloudmersive.InlineResponse20018FoundViruses);
    });

    it('should have the property fileName (base name: "FileName")', function() {
      // uncomment below and update the code to test the property fileName
      //var instane = new Cloudmersive.InlineResponse20018FoundViruses();
      //expect(instance).to.be();
    });

    it('should have the property virusName (base name: "VirusName")', function() {
      // uncomment below and update the code to test the property virusName
      //var instane = new Cloudmersive.InlineResponse20018FoundViruses();
      //expect(instance).to.be();
    });

  });

}));
