/**
 * Cloudmersive
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cloudmersive);
  }
}(this, function(expect, Cloudmersive) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cloudmersive.InlineResponse2005();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2005', function() {
    it('should create an instance of InlineResponse2005', function() {
      // uncomment below and update the code to test InlineResponse2005
      //var instane = new Cloudmersive.InlineResponse2005();
      //expect(instance).to.be.a(Cloudmersive.InlineResponse2005);
    });

    it('should have the property countryCode (base name: "CountryCode")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instane = new Cloudmersive.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property countryName (base name: "CountryName")', function() {
      // uncomment below and update the code to test the property countryName
      //var instane = new Cloudmersive.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "City")', function() {
      // uncomment below and update the code to test the property city
      //var instane = new Cloudmersive.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property regionCode (base name: "RegionCode")', function() {
      // uncomment below and update the code to test the property regionCode
      //var instane = new Cloudmersive.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property regionName (base name: "RegionName")', function() {
      // uncomment below and update the code to test the property regionName
      //var instane = new Cloudmersive.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property zipCode (base name: "ZipCode")', function() {
      // uncomment below and update the code to test the property zipCode
      //var instane = new Cloudmersive.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property timezoneStandardName (base name: "TimezoneStandardName")', function() {
      // uncomment below and update the code to test the property timezoneStandardName
      //var instane = new Cloudmersive.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property latitude (base name: "Latitude")', function() {
      // uncomment below and update the code to test the property latitude
      //var instane = new Cloudmersive.InlineResponse2005();
      //expect(instance).to.be();
    });

    it('should have the property longitude (base name: "Longitude")', function() {
      // uncomment below and update the code to test the property longitude
      //var instane = new Cloudmersive.InlineResponse2005();
      //expect(instance).to.be();
    });

  });

}));
