/**
 * Cloudmersive
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['invoker/ApiClient', 'invoker/model/InlineResponse2006'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/InlineResponse2006'));
  } else {
    // Browser globals (root is window)
    if (!root.Cloudmersive) {
      root.Cloudmersive = {};
    }
    root.Cloudmersive.LanguageDetectionApi = factory(root.Cloudmersive.ApiClient, root.Cloudmersive.InlineResponse2006);
  }
}(this, function(ApiClient, InlineResponse2006) {
  'use strict';

  /**
   * LanguageDetection service.
   * @module invoker/client/LanguageDetectionApi
   * @version 1.2.1
   */

  /**
   * Constructs a new LanguageDetectionApi. 
   * @alias module:invoker/client/LanguageDetectionApi
   * @class
   * @param {module:invoker/ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:invoker/ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the languageDetectionPost operation.
     * @callback module:invoker/client/LanguageDetectionApi~languageDetectionPostCallback
     * @param {String} error Error message, if any.
     * @param {module:invoker/model/InlineResponse2006} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Detect language of text
     * Automatically determine which language a text string is written in.  Supports Danish (DAN), German (DEU), English (ENG), French (FRA), Italian (ITA), Japanese (JPN), Korean (KOR), Dutch (NLD), Norwegian (NOR), Portuguese (POR), Russian (RUS), Spanish (SPA), Swedish (SWE), Chinese (ZHO).
     * @param {String} textToDetect Text to detect language of
     * @param {module:invoker/client/LanguageDetectionApi~languageDetectionPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:invoker/model/InlineResponse2006}
     */
    this.languageDetectionPost = function(textToDetect, callback) {
      var postBody = textToDetect;

      // verify the required parameter 'textToDetect' is set
      if (textToDetect === undefined || textToDetect === null) {
        throw new Error("Missing the required parameter 'textToDetect' when calling languageDetectionPost");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'];
      var accepts = ['application/json', 'text/json', 'application/xml', 'text/xml'];
      var returnType = InlineResponse2006;

      return this.apiClient.callApi(
        '/nlp/language/detect', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
