/**
 * Cloudmersive
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cloudmersive);
  }
}(this, function(expect, Cloudmersive) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cloudmersive.GenerateBarcodeApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GenerateBarcodeApi', function() {
    describe('generateBarcodeEAN13', function() {
      it('should call generateBarcodeEAN13 successfully', function(done) {
        //uncomment below and update the code to test generateBarcodeEAN13
        //instance.generateBarcodeEAN13(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('generateBarcodeEAN8', function() {
      it('should call generateBarcodeEAN8 successfully', function(done) {
        //uncomment below and update the code to test generateBarcodeEAN8
        //instance.generateBarcodeEAN8(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('generateBarcodeQRCode', function() {
      it('should call generateBarcodeQRCode successfully', function(done) {
        //uncomment below and update the code to test generateBarcodeQRCode
        //instance.generateBarcodeQRCode(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('generateBarcodeUPCA', function() {
      it('should call generateBarcodeUPCA successfully', function(done) {
        //uncomment below and update the code to test generateBarcodeUPCA
        //instance.generateBarcodeUPCA(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('generateBarcodeUPCE', function() {
      it('should call generateBarcodeUPCE successfully', function(done) {
        //uncomment below and update the code to test generateBarcodeUPCE
        //instance.generateBarcodeUPCE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
