/**
 * Cloudmersive
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cloudmersive);
  }
}(this, function(expect, Cloudmersive) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cloudmersive.SpellCheckApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SpellCheckApi', function() {
    describe('spellCheckCheckJson', function() {
      it('should call spellCheckCheckJson successfully', function(done) {
        //uncomment below and update the code to test spellCheckCheckJson
        //instance.spellCheckCheckJson(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('spellCheckCheckSentenceJson', function() {
      it('should call spellCheckCheckSentenceJson successfully', function(done) {
        //uncomment below and update the code to test spellCheckCheckSentenceJson
        //instance.spellCheckCheckSentenceJson(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('spellCheckCheckSentenceString', function() {
      it('should call spellCheckCheckSentenceString successfully', function(done) {
        //uncomment below and update the code to test spellCheckCheckSentenceString
        //instance.spellCheckCheckSentenceString(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('spellCheckCorrect', function() {
      it('should call spellCheckCorrect successfully', function(done) {
        //uncomment below and update the code to test spellCheckCorrect
        //instance.spellCheckCorrect(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('spellCheckCorrectJson', function() {
      it('should call spellCheckCorrectJson successfully', function(done) {
        //uncomment below and update the code to test spellCheckCorrectJson
        //instance.spellCheckCorrectJson(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('spellCheckPost', function() {
      it('should call spellCheckPost successfully', function(done) {
        //uncomment below and update the code to test spellCheckPost
        //instance.spellCheckPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
