/**
 * Cloudmersive
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cloudmersive);
  }
}(this, function(expect, Cloudmersive) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cloudmersive.WordsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WordsApi', function() {
    describe('wordsAdjectives', function() {
      it('should call wordsAdjectives successfully', function(done) {
        //uncomment below and update the code to test wordsAdjectives
        //instance.wordsAdjectives(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('wordsAdverbs', function() {
      it('should call wordsAdverbs successfully', function(done) {
        //uncomment below and update the code to test wordsAdverbs
        //instance.wordsAdverbs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('wordsGetWordsJson', function() {
      it('should call wordsGetWordsJson successfully', function(done) {
        //uncomment below and update the code to test wordsGetWordsJson
        //instance.wordsGetWordsJson(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('wordsGetWordsString', function() {
      it('should call wordsGetWordsString successfully', function(done) {
        //uncomment below and update the code to test wordsGetWordsString
        //instance.wordsGetWordsString(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('wordsNouns', function() {
      it('should call wordsNouns successfully', function(done) {
        //uncomment below and update the code to test wordsNouns
        //instance.wordsNouns(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('wordsPost', function() {
      it('should call wordsPost successfully', function(done) {
        //uncomment below and update the code to test wordsPost
        //instance.wordsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('wordsPronouns', function() {
      it('should call wordsPronouns successfully', function(done) {
        //uncomment below and update the code to test wordsPronouns
        //instance.wordsPronouns(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('wordsProperNouns', function() {
      it('should call wordsProperNouns successfully', function(done) {
        //uncomment below and update the code to test wordsProperNouns
        //instance.wordsProperNouns(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
